NUMPY(NUMERICAL PYTHON )

Discoverd in 2005
developed by Travis Oliphant
numpy is homogenous while list is hetrogen

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
#ndarray=n dimenstanal array 
#when we crearte any object with help of array method in numpy that obj called ndarray

In [3]:
import numpy as np  

In [4]:
arr=np.array(10)

In [5]:
x=10


In [6]:
type(x)

int

In [7]:
type(arr)

numpy.ndarray

In [9]:
#attributes::::
                #ndim----------->return dimensiom of an ndarray

In [10]:
arr.ndim

0

CREATE 1D NDARRAY

In [64]:
x=np.array([10,3,89,0])

In [65]:
x.ndim

1

In [66]:
x

array([10,  3, 89,  0])

In [67]:
#indexing

In [68]:
x[2]

89

CRAETE 2D NDARRAY

In [72]:
x=np.array([[19,90,87],[2,90,76]])

In [73]:
x.ndim

2

In [70]:
#indexing

In [74]:
x[0][2]

87

In [77]:
x[1][2]

76

In [78]:
x[0][2],x[1][2]

(87, 76)

CRAETE 3D NDARRAY

In [79]:
x=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [80]:
x.ndim

3

In [81]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

indexing

In [82]:
x[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
x[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [85]:
x[0][1][1]

5

CREATE 4D ARRAY

In [54]:
x=np.array([[[[1,2],[3,4],[5,6]]],[[[7,8],[9,8],[7,6]]],[[[5,4],[3,2],[1,0]]]])

In [55]:
x.ndim

4

In [56]:
type(x)

numpy.ndarray

In [57]:
x

array([[[[1, 2],
         [3, 4],
         [5, 6]]],


       [[[7, 8],
         [9, 8],
         [7, 6]]],


       [[[5, 4],
         [3, 2],
         [1, 0]]]])

slicing:::: with ndaary
objname[start:end:increment]


start:0
end:n-1
increment:1

In [86]:
c=np.array([3,6,7,6,6,45,6,7,9])

In [87]:
c[2:6]

array([ 7,  6,  6, 45])

In [88]:
c[: :-1]

array([ 9,  7,  6, 45,  6,  6,  7,  6,  3])

SLICING IN 2D

In [89]:
x=np.array([[19,90,87],[2,90,76]])

In [91]:
x[1][1:3]

array([90, 76])

slicing in 3d

In [92]:
x=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [94]:
x[1][1][2]

12

ndarrray----------------->>>> mutable

In [96]:
z=np.array([12,56,48,59,90])

In [97]:
#replacing elements

In [99]:
#objname[indexnumber]=newitem

In [103]:
z[-1]=8

In [104]:
z

array([12, 56, 48, 59,  8])

In [105]:



#add elements

#append


In [109]:
z=np.array([2,4,3,5,4])

In [110]:
p=np.append(z,39)

In [111]:
p

array([ 2,  4,  3,  5,  4, 39])

In [114]:
#insert ---------->at specfic index
#np.insert(objname,indexname,item)


In [115]:
np.insert(p,3,8)

array([ 2,  4,  3,  8,  5,  4, 39])

In [116]:
index=[3,4,6]
element=[3,6,4]

In [118]:
np.insert(p,index,element)

array([ 2,  4,  3,  3,  5,  6,  4, 39,  4])