NUMPY(NUMERICAL PYTHON )

Discoverd in 2005
developed by Travis Oliphant
numpy is homogenous while list is hetrogen

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
#ndarray=n dimenstanal array 
#when we create any object with help of array method in numpy that obj called ndarray

In [3]:
import numpy as np  

In [4]:
arr=np.array(10)

In [5]:
x=10


In [6]:
type(x)

int

In [7]:
type(arr)

numpy.ndarray

In [9]:
#attributes::::
                #ndim----------->return dimensiom of an ndarray

In [10]:
arr.ndim

0

CREATE 1D NDARRAY

In [64]:
x=np.array([10,3,89,0])

In [65]:
x.ndim

1

In [66]:
x

array([10,  3, 89,  0])

In [67]:
#indexing

In [68]:
x[2]

89

CRAETE 2D NDARRAY

In [72]:
x=np.array([[19,90,87],[2,90,76]])

In [73]:
x.ndim

2

In [70]:
#indexing

In [74]:
x[0][2]

87

In [77]:
x[1][2]

76

In [78]:
x[0][2],x[1][2]

(87, 76)

CRAETE 3D NDARRAY

In [79]:
x=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [80]:
x.ndim

3

In [81]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

indexing

In [82]:
x[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
x[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [85]:
x[0][1][1]

5

CREATE 4D ARRAY

In [54]:
x=np.array([[[[1,2],[3,4],[5,6]]],[[[7,8],[9,8],[7,6]]],[[[5,4],[3,2],[1,0]]]])

In [55]:
x.ndim

4

In [56]:
type(x)

numpy.ndarray

In [57]:
x

array([[[[1, 2],
         [3, 4],
         [5, 6]]],


       [[[7, 8],
         [9, 8],
         [7, 6]]],


       [[[5, 4],
         [3, 2],
         [1, 0]]]])

slicing:::: with ndaary
objname[start:end:increment]


start:0
end:n-1
increment:1

In [86]:
c=np.array([3,6,7,6,6,45,6,7,9])

In [87]:
c[2:6]

array([ 7,  6,  6, 45])

In [88]:
c[: :-1]

array([ 9,  7,  6, 45,  6,  6,  7,  6,  3])

SLICING IN 2D

In [89]:
x=np.array([[19,90,87],[2,90,76]])

In [91]:
x[1][1:3]

array([90, 76])

slicing in 3d

In [92]:
x=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [94]:
x[1][1][2]

12

ndarrray----------------->>>> mutable

In [96]:
z=np.array([12,56,48,59,90])

In [97]:
#replacing elements

In [99]:
#objname[indexnumber]=newitem

In [103]:
z[-1]=8

In [104]:
z

array([12, 56, 48, 59,  8])

In [105]:



#add elements

#append


In [109]:
z=np.array([2,4,3,5,4])

In [110]:
p=np.append(z,39)

In [111]:
p

array([ 2,  4,  3,  5,  4, 39])

In [114]:
#insert ---------->at specfic index
#np.insert(objname,indexname,item)


In [115]:
np.insert(p,3,8)

array([ 2,  4,  3,  8,  5,  4, 39])

In [116]:
index=[3,4,6]
element=[3,6,4]

In [118]:
np.insert(p,index,element)

array([ 2,  4,  3,  3,  5,  6,  4, 39,  4])

In [119]:

#tab is used for 
#methods

In [120]:
#where() it return index number

In [121]:
x=np.array([10,3,89,0])

In [122]:
np.where(x==3)

(array([1], dtype=int64),)

In [125]:
help(np.arange)#help is used for documentation

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [128]:
#arange


#arange(start,end,increment)

In [131]:
x=np.arange(1,15,1)

In [132]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [133]:
#sort

In [136]:
x=np.array([12,65,43,6,5,9])

In [137]:
np.sort(x)

array([ 5,  6,  9, 12, 43, 65])

In [140]:
#unique  help us to get unique data


In [143]:
x=np.array([12,65,43,4,5,3,23,12,6,5,9])

In [144]:
np.unique(x)

array([ 3,  4,  5,  6,  9, 12, 23, 43, 65])

In [145]:
#concatenate

In [149]:
p=np.array([2,5,4,3,5])


In [155]:
q=np.array([2,7,5,4,6])

In [156]:
np.concatenate((p,q))

array([2, 5, 4, 3, 5, 2, 7, 5, 4, 6])

In [157]:
#vstack

In [158]:
np.vstack((p,q))

array([[2, 5, 4, 3, 5],
       [2, 7, 5, 4, 6]])

In [1]:
# reshape----

In [23]:
x=np.array([12,65,43,4,5,3,23,12,6,5,9,3])

In [24]:
len(x)

12

In [25]:
x.reshape(2,6)

array([[12, 65, 43,  4,  5,  3],
       [23, 12,  6,  5,  9,  3]])

In [26]:
x.reshape((2,-1))

array([[12, 65, 43,  4,  5,  3],
       [23, 12,  6,  5,  9,  3]])

In [27]:
x.reshape(-1,4)

array([[12, 65, 43,  4],
       [ 5,  3, 23, 12],
       [ 6,  5,  9,  3]])

In [29]:
#1d to 3d rehaping

In [30]:
x.reshape(2,3,2)

array([[[12, 65],
        [43,  4],
        [ 5,  3]],

       [[23, 12],
        [ 6,  5],
        [ 9,  3]]])

In [22]:
x.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
3d array reshaping

In [13]:
x=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [15]:
x.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
x.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [31]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])


In [33]:

x = np.where(arr == 4)

In [34]:
print(x)

(array([3, 5, 6], dtype=int64),)


In [35]:
#random

In [36]:
from numpy import random

In [ ]:
randit retunn value upto specfic age

In [38]:
random.randint(100)

22

In [41]:
random.randint(8,67,size=(5))

array([53, 61, 58, 16, 31])

In [42]:
random.randint(8,67,size=(5,4))#2d

array([[21, 33, 48, 13],
       [66, 30, 60, 47],
       [29, 36, 49, 41],
       [45, 53, 21, 36],
       [50, 58, 25, 32]])

In [43]:
random.randint(8,67,size=(5,2,1))#3d

array([[[58],
        [ 9]],

       [[53],
        [22]],

       [[58],
        [21]],

       [[21],
        [18]],

       [[31],
        [16]]])

In [44]:
#random.rand--it return random value from 0 and 1

In [45]:
random.rand(3)

array([0.14850603, 0.67591642, 0.94975095])

In [46]:
#choice -no range

In [50]:
xp=random.choice([2,5,4,3,36,7,4,3,3],size=(3,3))
xp

array([[ 3,  4, 36],
       [ 2,  4,  4],
       [ 3, 36,  4]])

In [59]:
x=1234452
def xyz(*x):
    lst = list(x)
    dic = {}
    
    for i in lst:
        if i not in dic and lst.count(i) != 1:
            dic[i] = lst.count(i)
    
  


In [66]:
  print(lst)

NameError: name 'lst' is not defined

In [65]:
x=1234567

In [1]:
print

<function print(*args, sep=' ', end='\n', file=None, flush=False)>